### ISSUE TITLE
How to get the last song file form sinsy.jp

### ISSUE THREAD

**Issue by YuzukiTsuru** [mathigatti/midi2voice#1]
How to get the last song file form sinsy.jp
and I want ro rewrite it into py3 ^v^

**Comment by mathigatti** [comment]
do you mean how the script downloads the generated wav after it uploads de .xml?
It's done in this [line](https://github.com/mathigatti/midi2voice/blob/32e608ba17b73bc960d97e0a4a4f61cbc36db0a2/voice.sh#L8), there I am uploading the .xml, receiving the output and extracting the line where says "lf0" which is where the url of the generated wav is located.

**Comment by mathigatti** [comment]
That would be great if you migrate it into py3 :)

**Comment by YuzukiTsuru** [comment]
Thanks 👍

**Comment by mathigatti** [comment]
I did some code improvements I will try to update the repository today.

**Comment by mathigatti** [comment]
I improved a little bit the code and removed some dependencies.
