### ISSUE TITLE
The colab tutorial fails to install the package

### ISSUE THREAD

**Issue by VehpuS** [mathigatti/midi2voice#10]
Hi.

This is such a cool package ;). I tested first via the [colab link](https://colab.research.google.com/drive/1_lZiwQfuHIVaEFmAibPKUMprZ_0yU35L?usp=sharing) provided in the repo's README but colab failed to connect to github, so instead I did the following:

```
!git clone https://github.com/mathigatti/midi2voice.git
!pip install /content/midi2voice/
```

[A gist demonstrating the change](https://gist.github.com/VehpuS/bd4c802ff6e6c3001af92dc9ec9a91b9).

I figured I'd mention it in an issue in case you want to fix it ;).

Kudos again for the package!

**Comment by mathigatti** [comment]
oh thank you very much for notifying it! That works, I updated the code to something similar, now it makes this:

!pip install git+https://github.com/mathigatti/midi2voice.git

I think there was a typo in the old colab or something.
