### ISSUE TITLE
Hello Mathigatti

### ISSUE THREAD

**Issue by scranley** [mathigatti/midi2voice#11]
I tested out the project yesterday, and I am quite amazed. I made a test midi with text and it sang so nice.  Now I can't seem to reach the voice server. I would def be willing to send you some money on paypay if you can help me make it more fault tolerant, I would also buy a voice somewhere if I could. 

MaxRetryError: HTTPConnectionPool(host='sinsy.sp.nitech.ac.jp', port=80): Max retries exceeded with url: /index.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002C0C0A386D0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

**Comment by mathigatti** [comment]
were you able to fix it? Seems like sinsy.jp is down, hopefully they will fix it soon.

**Comment by scranley** [comment]
I was able to compile it on my ubuntu 18 server. i ran the sample xml. it
outputted a working wav file.  couldnt get any docs on how to set it up as
a server like sinsy so it will work with your script.  i assume some cgi
setup. or just mod your script to output xml and copy the xml to the
server. and do it manually.  im looking to automate it with jenkins so i
could still def pay you to help get it working completly.

**Comment by scranley** [comment]
Hello Mathias,  thanks for your help, I'll just use what I have. Sorry I
didn't have time to think. Thank you for getting me this far.

**Comment by mathigatti** [comment]
Hey, sorry, quick question. So you were able to run sinsy for english on your own server? Do you have some guide about how you did it?

**Comment by scranley** [comment]
Hey! I'll go look, im super busy right now, but I really want to give back
to what you helped with, so def want to do it.

**Comment by mathigatti** [comment]
thanks!

**Comment by cranley-seamus** [comment]
Hey sorry just saw this by mistake lol, do you still need it?
