### ISSUE TITLE
Questions about Japanese/Mandarin Text Preprocessing

### ISSUE THREAD

**Issue by ORI-Muchim** [mathigatti/midi2voice#12]
Hello! I contacted you after checking your repo. It's just that there seems to be no dictionary in the 'pyphen' library that handles Japanese and Mandarin, but I wonder how you handled it. Thank you in advance.

**Comment by mathigatti** [comment]
hey! Yeah, I'm not familiar with japanese and mandarin, maybe something that converts these languages to phonemes and then something that splits that into syllables might work but it would be nice to get some help from someone that speaks the language

**Comment by ORI-Muchim** [comment]
<img width="544" alt="image" src="https://github.com/mathigatti/midi2voice/assets/92266719/72ebbe3c-6706-453e-93e2-a7b60ac488de">

Yes. I'll check that part. Can I ask you one more question? This problem is continuing. Is there a solution?

**Comment by ORI-Muchim** [comment]
The problem solved when I changed the text encoding method. Thank you!
