### ISSUE TITLE
Why even the example you give on Soundcloud sing wrong lyrics?

### ISSUE THREAD

**Issue by aletote** [mathigatti/midi2voice#3]
Just that. It doesnt even start properly with "now and then"...

**Comment by mathigatti** [comment]
Right now the lyrics logic consist of mapping each word in the lyrics to each note in the melody, that is a really simple approach that doesn't work so well usually, I can try to improve it later.

Anyway I don't know why the lyrics doesn't start with "now and then", that shouldn't happen, I will check it :)

**Comment by mathigatti** [comment]
I improved it and updated the example, let me know. It's not perfect but it's much better.

**Comment by aletote** [comment]
Like you said much much better. Not perfect yet but much better. Listening to Shallow I noticed a problem at 2:26  and is that there, at the bridge, she sings "ahh ahh ahh ahhh" but your program just gives it the next chorus lyrics and then all the lyrics get the wrong time again but I guess that's fixable adding those "ahh"s in the input lyric.

**Comment by mathigatti** [comment]
Thanks just improved the lyrics txt based on your suggestions and improved a little bit more the lyrics tokenization. Feel free to reopen the issue if you find something more.
