### ISSUE TITLE
Where these files are?

### ISSUE THREAD

**Issue by Kyosuke3635** [mathigatti/midi2voice#4]
I can't find "temp.xml", "voice.xml" and "voice.wav".
I've studied about voice synthesis and python for only few days, so I can't understand your great code.
If you can, please tell me the meaning of "midi2xml, line 9" , e.t.c...
And please tell me where can I get these files.

**Comment by mathigatti** [comment]
Hi! Those files should be generated when you execute the program.

_voice.wav_ is the end result of the program, the synthesized voice. 

temp.xml and voice.xml are just intermediate files, used to generate voice.wav, those are text files which specify the notes and syllables of the voice.

**Comment by Kyosuke3635** [comment]
temp.xml and voice.xml are made in the program?
I have an error like that.
"FileNotFoundError: [Errno 2] No such file or directory: 'temp.xml'"
Because of it, I thought I need to prepare them.

**Comment by mathigatti** [comment]
can you share the full command line output? What's your operative system? Maybe you don't have musescore installed?

**Comment by Kyosuke3635** [comment]
>python3 midi2voice.py ./inputs/shallow.txt ./inputs/shallow.mid female 96

/Applications/anaconda3/lib/python3.7/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Running voice renderization
sh: musescore: command not found
Traceback (most recent call last):
  File "midi2voice.py", line 80, in <module>
    main()
  File "midi2voice.py", line 77, in main
    renderizeVoice(lyrics,midiPath,sex, tempo)
  File "midi2voice.py", line 15, in renderizeVoice
    midi2xml(lyrics,midiPath,VOICE_XML,tempo)
  File "/Users/****/midi2voice-master/midi2xml.py", line 12, in midi2xml
    generateVoiceSpecification(lyrics,tempo,tempXML,xmlPath)
  File "/Users/****/midi2voice-master/midi2xml.py", line 19, in generateVoiceSpecification
    with open(inputMusicXMLPath, 'r') as c:
FileNotFoundError: [Errno 2] No such file or directory: 'temp.xml'



My OS is MacOS and I installed musescore, but I probably failed installing to execute the program.

**Comment by mathigatti** [comment]
The program basically executes something like this `musescore your_midi.mid -o temp.xml` in order to generate the temp.xml file. You can try running that in your terminal, I guess it's going to fail too. [Shaun Kane](https://github.com/shaunkane/midi2voice/blob/f4835284672604dc81fb84c07496400dc60ec7f7/midi2voice.py#L68) modified my code for osx and it looks like it was fixed after changing a little bit the command. Replacing it to this `mscore your_midi.mid -o temp.xml`

Try running those commands in your terminal and let me know how that goes :)

**Comment by Kyosuke3635** [comment]
Thanks!!!
I'll try now!

**Comment by Kyosuke3635** [comment]
It succeed!!!!
Thank you so much!
And I'll use your codes continuously for my study!

**Comment by mathigatti** [comment]
awesome :) you're welcome
